/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sws;

import org.junit.jupiter.api.Test;

class SimpleLoginTest {
    @Test void someLibraryMethodReturnsTrue() {
    }
}
